# ========================================
# PROD Profile
# ========================================
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=true
spring.devtools.restart.enabled=false

# Logging
logging.level.fit.hutech.HuynhLeHongXuyen=INFO
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=WARN

# Server
server.error.include-stacktrace=never
server.error.include-message=never
