# ========================================
# DEV Profile
# ========================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true

# Logging
logging.level.fit.hutech.HuynhLeHongXuyen=DEBUG
logging.level.org.springframework.security=DEBUG
